# Project 4

## Task 1

In [1]:
from bs4 import BeautifulSoup
import requests
import pandas as pd

In [2]:
link = "https://en.wikipedia.org/wiki/List_of_states_and_territories_of_the_United_States"

In [3]:
webpage = requests.get(link).text

In [4]:
webpage = BeautifulSoup(webpage, "html.parser")

#### The data we are looking for is inside a table element wiith the class name "wikitable sortable plainrowheaders"

In [5]:
table = webpage.find("table", class_="wikitable sortable plainrowheaders")

## Task 2

In [6]:
th_tags = table.find_all('th', scope="row")

In [7]:
state_names = []
for th in th_tags:
    a_tag = th.find('a')
    state_names.append(a_tag.string)

In [8]:
state_names

['Alabama',
 'Alaska',
 'Arizona',
 'Arkansas',
 'California',
 'Colorado',
 'Connecticut',
 'Delaware',
 'Florida',
 'Georgia',
 'Hawaii',
 'Idaho',
 'Illinois',
 'Indiana',
 'Iowa',
 'Kansas',
 'Kentucky',
 'Louisiana',
 'Maine',
 'Maryland',
 'Massachusetts',
 'Michigan',
 'Minnesota',
 'Mississippi',
 'Missouri',
 'Montana',
 'Nebraska',
 'Nevada',
 'New Hampshire',
 'New Jersey',
 'New Mexico',
 'New York',
 'North Carolina',
 'North Dakota',
 'Ohio',
 'Oklahoma',
 'Oregon',
 'Pennsylvania',
 'Rhode Island',
 'South Carolina',
 'South Dakota',
 'Tennessee',
 'Texas',
 'Utah',
 'Vermont',
 'Virginia',
 'Washington',
 'West Virginia',
 'Wisconsin',
 'Wyoming']

## Task 3

In [9]:
tr_tags = []

In [10]:
for th in th_tags:
    tr_tags.append(th.parent)

In [11]:
state_populations = []

In [12]:
for tr in tr_tags:
    td_tags = tr.find_all("td")
    population_div = td_tags[-4].find("div")
    state_populations.append(population_div.string)

In [13]:
state_populations

['5,024,279',
 '733,391',
 '7,151,502',
 '3,011,524',
 '39,538,223',
 '5,773,714',
 '3,605,944',
 '989,948',
 '21,538,187',
 '10,711,908',
 '1,455,271',
 '1,839,106',
 '12,812,508',
 '6,785,528',
 '3,190,369',
 '2,937,880',
 '4,505,836',
 '4,657,757',
 '1,362,359',
 '6,177,224',
 '7,029,917',
 '10,077,331',
 '5,706,494',
 '2,961,279',
 '6,154,913',
 '1,084,225',
 '1,961,504',
 '3,104,614',
 '1,377,529',
 '9,288,994',
 '2,117,522',
 '20,201,249',
 '10,439,388',
 '779,094',
 '11,799,448',
 '3,959,353',
 '4,237,256',
 '13,002,700',
 '1,097,379',
 '5,118,425',
 '886,667',
 '6,910,840',
 '29,145,505',
 '3,271,616',
 '643,077',
 '8,631,393',
 '7,705,281',
 '1,793,716',
 '5,893,718',
 '576,851']

## Task 4

In [14]:
state_data = pd.DataFrame({"state": state_names, "population": state_populations})

In [15]:
state_data

             state  population
0          Alabama   5,024,279
1           Alaska     733,391
2          Arizona   7,151,502
3         Arkansas   3,011,524
4       California  39,538,223
5         Colorado   5,773,714
6      Connecticut   3,605,944
7         Delaware     989,948
8          Florida  21,538,187
9          Georgia  10,711,908
10          Hawaii   1,455,271
11           Idaho   1,839,106
12        Illinois  12,812,508
13         Indiana   6,785,528
14            Iowa   3,190,369
15          Kansas   2,937,880
16        Kentucky   4,505,836
17       Louisiana   4,657,757
18           Maine   1,362,359
19        Maryland   6,177,224
20   Massachusetts   7,029,917
21        Michigan  10,077,331
22       Minnesota   5,706,494
23     Mississippi   2,961,279
24        Missouri   6,154,913
25         Montana   1,084,225
26        Nebraska   1,961,504
27          Nevada   3,104,614
28   New Hampshire   1,377,529
29      New Jersey   9,288,994
30      New Mexico   2,117,522
31        New York  20,201,249
32  North Carolina  10,439,388
33    North Dakota     779,094
34            Ohio  11,799,448
35        Oklahoma   3,959,353
36          Oregon   4,237,256
37    Pennsylvania  13,002,700
38    Rhode Island   1,097,379
39  South Carolina   5,118,425
40    South Dakota     886,667
41       Tennessee   6,910,840
42           Texas  29,145,505
43            Utah   3,271,616
44         Vermont     643,077
45        Virginia   8,631,393
46      Washington   7,705,281
47   West Virginia   1,793,716
48       Wisconsin   5,893,718
49         Wyoming     576,851

In [16]:
state_data.to_csv("us_info.csv")